import type { GetStaticProps } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import { Skills }  from '../components/Skills'
import  Projects  from '../components/Projects'
import ContactMe from '../components/ContactMe'
import { Skill, Project } from '../typings'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchProjects } from '../utils/fetchProjects'

type Props = {
  skills: Skill[];
  projects: Project[];
}

const Home = ({projects, skills}: Props) => {
  return (
    <div className='bg-[rgb(36,36,36)] h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0
    scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#088F8F]/80'>
      <Head>
        <title>Cyril Muchemi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <section id='hero' className='snap-start'>
      <Hero/>
      </section>
      <section id='about' className='snap-center'>
        <About/>
      </section>
      <section id='skills' className='snap-center'>
        <Skills/>
      </section>
      <section id='projects' className='snap-start'>
        <Projects projects={projects}/>
      </section>
      <section id='contact' className='snap-start'>
        <ContactMe/>
      </section>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps<Props> = async () => {
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();

  return {
    props: {
      skills,
      projects
    },
    revalidate: 10
  };
}

